services:
  - type: web
    name: istedalis
    runtime: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
